### ISSUE TITLE
지정한 경로의 내용물을 구글드라이브에 업로드

### ISSUE THREAD

**Issue by eddie94** [Dev-Ai-Lopers/DL-Utils#1]
# 개요

사용자로부터 경로를 입력받아 구글드라이브에 업로드할 수 있는 함수를 작성

# 관련 이슈

없음

# 완료 조건

해당 이슈를 달성하기 위한 조건을 기술

- [ ] 지정한 경로의 내용물이 구글 드라이브에 업로드 됐는지 확인
- [ ] 사용자 로그인 방식에 대한 설계
- [ ] 코드 동작 확인

**Comment by eddie94** [comment]
해당 함수는 dlutils/logging/ 안에 작성할것

**Comment by txuna** [comment]
@eddie94 업로드할 때의 파일 타입 종류는 정해져 있나요?
ex) txt, jpeg, png

**Comment by eddie94** [comment]
@txuna 
경로를 지정해서 안의 내용물을 복사하는 형태라
파일이랑 디렉토리를 recursive하게 업로드해야 됩니다
따라서 파일 타입 종류는 딱히 지저알것 같지는 않네요

**Comment by txuna** [comment]
@eddie94 
재귀적으로 디렉토리를 탐색하여 파일을 업로드할 때 파일의 이름에 확장자가 무조건적으로 있다고 가정하면 되나요?
그것이 아니라면 확장자가 없는 파일에 한에서는 txt/plain 형태로 업로드 해도될까요?

확장자를 기반으로 어떤 파일인지 메타데이터를 업로드시에 필수인자로 되어있습니다

**Comment by eddie94** [comment]
@txuna 
확장자가 없는파일은 txt로 예외처리항을 넣는게 좋아보입니다
보통 확장자가 없는 경우는 거의 없을것 같습니다

**Comment by eddie94** [comment]
#2 머지 완료했으므로 이슈 종료
