### ISSUE TITLE
구글 드라이브 API 사용시 확장자 문제 테스트

### ISSUE THREAD

**Issue by eddie94** [Dev-Ai-Lopers/DL-Utils#3]
# 개요

구글 드라이브가 지원하는 확장자가 아닌 파일을 업로드 했을때 생기는 동작을 확인

# 관련 이슈

#1 

# 완료 조건

해당 이슈를 달성하기 위한 조건을 기술

- [x] 이미지 파일 등, 텍스트가 아닌 파일을 구글 드라이브 API를 통해 업로드하고 다시 다운 받았을때 정상적으로 열리는지 확인

**Comment by txuna** [comment]
@eddie94 테스트결과 이미지 파일을 text/plain 미디어 타입으로 구글드라이브에 업로드하였을 때 드라이브 내에서는 텍스트파일로 인식하나 다운로드시 확장자가 남아있기 때문에 로컬에서는 이미지로 인식됩니다

테스트 플랫폼 
1. Windows 11 

테스트 케이스 
1. .jpeg 파일 media type을 text/plain으로 설정 후 업로드 
2. 구글드라이브내에서는 text/plain으로 인식 
3. 다운로드후 로컬에서는 jpeg확장자가 남아있기에 JPEG파일로 인식
